<%@page contentType="text/html" pageEncoding="UTF-8" import="java.sql.*,com.j4u.DatabaseConfig"%>
<% String user=(String)session.getAttribute("lname"); if(user==null){response.sendRedirect("../auth/Login.jsp");return;} String msg=""; if("POST".equalsIgnoreCase(request.getMethod())){ try(Connection con=DatabaseConfig.getConnection()){ PreparedStatement ps=con.prepareStatement("UPDATE lawyer_reg SET name=?, mobile=?, cadd=?, specialization=?, experience_years=?, bar_council_number=? WHERE email=?"); ps.setString(1,request.getParameter("name")); ps.setString(2,request.getParameter("mobile")); ps.setString(3,request.getParameter("cadd")); ps.setString(4,request.getParameter("spec")); ps.setString(5,request.getParameter("exp")); ps.setString(6,request.getParameter("bar")); ps.setString(7,user); ps.executeUpdate(); msg="Profile updated successfully!"; }catch(Exception e){msg="Error:"+e.getMessage();} } String name="", mobile="", cadd="", spec="", exp="", bar="", status="PENDING"; try(Connection con=DatabaseConfig.getConnection()){ PreparedStatement ps=con.prepareStatement("SELECT * FROM lawyer_reg WHERE email=?"); ps.setString(1,user); ResultSet rs=ps.executeQuery(); if(rs.next()){ name=rs.getString("name"); if(name==null) name=rs.getString("fname")+""+rs.getString("lname"); mobile=rs.getString("mobile"); cadd=rs.getString("cadd"); spec=rs.getString("specialization"); exp=rs.getString("experience_years"); bar=rs.getString("bar_council_number"); status=rs.getString("status"); } }catch(Exception e){}
%>
<!DOCTYPE html>
<html lang="en">
<jsp:include page="components/_head.jsp"><jsp:param name="title" value="My Profile"/></jsp:include>
<body>
<div class="app-layout"> <jsp:include page="components/_sidebar.jsp"><jsp:param name="active" value="profile"/></jsp:include> <main class="main-content"> <jsp:include page="components/_topbar.jsp"><jsp:param name="title" value="My"/><jsp:param name="subtitle" value="Profile"/></jsp:include> <div class="px-4"> <% if(!msg.isEmpty()){ %><div class="mb-4 border rounded bg-light small"><%=msg%></div><% } %> <form method="POST" class="panel p-4"> <div class="row g-3"> <div class="col-md-6"><label class="small mb-1">Full Name</label><input type="text" name="name" class="form-control" value="<%=name%>" required></div> <div class="col-md-6"><label class="small mb-1">Mobile</label><input type="text" name="mobile" class="form-control" value="<%=mobile==null?"":mobile%>" required></div> <div class="col-md-6"><label class="small mb-1">Bar Number</label><input type="text" name="bar" class="form-control" value="<%=bar==null?"":bar%>" required></div> <div class="col-md-6"><label class="small mb-1">Experience (Years)</label><input type="number" name="exp" class="form-control" value="<%=exp==null?"0":exp%>" required></div> <div class="col-12"><label class="small mb-1">City</label><input type="text" name="cadd" class="form-control" value="<%=cadd==null?"":cadd%>" required></div> <div class="col-12"><label class="small mb-1">Specializations</label><textarea name="spec" class="form-control" rows="2" required><%=spec==null?"":spec%></textarea></div> <div class="col-12"><button type="submit" class="btn btn-dark w-100 mt-2">Update Profile</button></div> </div> </form> </div> </main>
</div>
</body>
</html>
