<%--
    Document   : final_password_reset
    Created on : Final password reset with working hash
    Author     : Admin Utility
--%>
<%@page contentType="text/html" pageEncoding="UTF-8" import="java.sql.*"%>
<%@ include file="../shared/db_connection.jsp" %>
<%
    try
    {
        // Class.forName("com.mysql.jdbc.Driver");
        Connection con = getDatabaseConnection();
        out.println("<h1>Final Password Reset</h1>");
        // Use a known working hash for "test123"
        // This hash was generated by PasswordUtil.hashPassword("test123") and verified to work
        String workingHash = "THUjF7vlH9YvP+FT9/2oFGFbnrPkNF2pDm2e8CGVHghnDb542DzDOALBVJA5ZKnl";
        out.println("<p><strong>Setting password to:</strong> test123</p>");
        out.println("<p><strong>Using hash:</strong> " + workingHash + "</p>");
        // Update the password directly
        String updateQuery = "UPDATE cust_reg SET pass = ? WHERE email = ?";
        PreparedStatement pst = con.prepareStatement(updateQuery);
        pst.setString(1, workingHash);
        pst.setString(2, "client242@gmail.com");
        int rowsAffected = pst.executeUpdate();
        out.println("<p><strong>Rows Updated:</strong> " + rowsAffected + "</p>");
        if (rowsAffected > 0) {
            out.println("<h2 style='color:green;'>âœ“ Password Reset Successful</h2>");
            // Verify it works
            String verifyQuery = "SELECT pass FROM cust_reg WHERE email = ?";
            PreparedStatement verifyPst = con.prepareStatement(verifyQuery);
            verifyPst.setString(1, "client242@gmail.com");
            ResultSet rs = verifyPst.executeQuery();
            if (rs.next()) {
                String storedHash = rs.getString("pass");
                out.println("<p><strong>Stored Hash After Update:</strong> " + storedHash + "</p>");
                // Test the verification
                boolean testVerify = com.j4u.PasswordUtil.verifyPassword("test123", storedHash);
                out.println("<p><strong>Verification Test:</strong> <span style='color:" + (testVerify ? "green" : "red") + "; font-weight:bold;'>" + testVerify + "</span></p>");
                if (testVerify) {
                    out.println("<h3 style='color:green;'>âœ“ SUCCESS - You can now login!</h3>");
                    out.println("<p><strong>Login Credentials:</strong></p>");
                    out.println("<ul>");
                    out.println("<li><strong>Email:</strong> client242@gmail.com</li>");
                    out.println("<li><strong>Password:</strong> test123</li>");
                    out.println("</ul>");
                } else {
                    out.println("<h3 style='color:red;'>âœ— VERIFICATION FAILED</h3>");
                }
            }
            rs.close();
            verifyPst.close();
        } else {
            out.println("<h2 style='color:red;'>âœ— Password Reset Failed</h2>");
        }
        pst.close();
        con.close();
    }
    catch(Exception ee)
    {
        out.println("<h1 style='color:red;'>Database Error</h1>");
        out.println("<p>Error: " + ee.getMessage() + "</p>");
        ee.printStackTrace();
    }
%>
